version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: liquibase
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  liquibase:
    image: liquibase/liquibase
    container_name: liquibase_container
    depends_on:
      - mysql
    volumes:
      - ./changelog:/liquibase/changelog
      - ./liquibase.properties:/liquibase/liquibase.properties
    command: --defaultsFile=/liquibase/liquibase.properties
